#!/usr/bin/env python3
"""Generate viewer/render/colormaps_data.h with 256-entry RGB lookup tables.

Run once by a developer; the output header is committed. Requires matplotlib.

    python3 tools/gen_colormaps.py > viewer/render/colormaps_data.h

M1 ships the perceptually-uniform maps viridis and turbo. Later milestones extend
this list (magma, cividis, cmocean-*, stepped meteorology maps).
"""
import sys

import matplotlib
import numpy as np

MAPS = ["viridis", "turbo"]
N = 256


def table(name):
    cmap = matplotlib.colormaps[name]
    rows = []
    for i in range(N):
        r, g, b, _ = cmap(i / (N - 1))
        rows.append((round(r * 255), round(g * 255), round(b * 255)))
    return rows


def main():
    out = sys.stdout
    out.write("// Generated by tools/gen_colormaps.py. Do not edit by hand.\n")
    out.write("#pragma once\n\n")
    out.write("#include <cstdint>\n\n")
    out.write("namespace met::render::detail {\n\n")
    out.write(f"inline constexpr int kColormapSize = {N};\n\n")
    for name in MAPS:
        rows = table(name)
        out.write(f"inline constexpr std::uint8_t k_{name}[{N}][3] = {{\n")
        for (r, g, b) in rows:
            out.write(f"    {{{r}, {g}, {b}}},\n")
        out.write("};\n\n")
    out.write("}  // namespace met::render::detail\n")


if __name__ == "__main__":
    main()
