# clang-format integration: `format` rewrites sources in place, `format-check`
# reports what would change and fails, which is what CI gates on.
#
# Both targets are optional — if no clang-format is found the build is unaffected
# and only a status message is emitted, so a missing formatter never blocks
# someone from building the app.

# The version the tree is formatted with. clang-format's output is not stable
# across major releases, so a mismatched binary will flag differences that are
# the tool's, not the author's — the single most common way a format gate turns
# into permanent CI noise. CI installs exactly this via pip (see ci.yml); keep
# the two in sync when bumping.
set(MET_CLANG_FORMAT_VERSION "21.1.8")
string(REGEX MATCH "^[0-9]+" MET_CLANG_FORMAT_MAJOR "${MET_CLANG_FORMAT_VERSION}")

find_program(MET_CLANG_FORMAT
    NAMES clang-format-${MET_CLANG_FORMAT_MAJOR} clang-format
    DOC "clang-format executable used by the format / format-check targets")

if(NOT MET_CLANG_FORMAT)
    message(STATUS "clang-format not found — 'format' and 'format-check' targets unavailable")
    return()
endif()

execute_process(COMMAND ${MET_CLANG_FORMAT} --version
    OUTPUT_VARIABLE _met_cf_version_output
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET)
string(REGEX MATCH "([0-9]+)\\.[0-9]+\\.[0-9]+" _met_cf_found "${_met_cf_version_output}")
set(_met_cf_found_major "${CMAKE_MATCH_1}")

if(NOT _met_cf_found_major STREQUAL MET_CLANG_FORMAT_MAJOR)
    message(WARNING
        "clang-format ${_met_cf_found_major}.x found, but this tree is formatted with "
        "${MET_CLANG_FORMAT_VERSION}. Formatting will disagree with CI. Install the pinned "
        "version with:  pip install clang-format==${MET_CLANG_FORMAT_VERSION}")
endif()

# Sources to format: everything hand-written under viewer/ and tests/.
# CONFIGURE_DEPENDS re-globs when files are added, so a new file cannot slip past
# the check just because nobody re-ran cmake by hand.
file(GLOB_RECURSE MET_FORMAT_SOURCES CONFIGURE_DEPENDS
    "${CMAKE_SOURCE_DIR}/viewer/*.cpp"
    "${CMAKE_SOURCE_DIR}/viewer/*.h"
    "${CMAKE_SOURCE_DIR}/tests/*.cpp"
    "${CMAKE_SOURCE_DIR}/tests/*.h")

# colormaps_data.h is generated by tools/gen_colormaps.py; reformatting it would
# be undone by the next regeneration and adds 1500 lines of noise to any diff.
list(FILTER MET_FORMAT_SOURCES EXCLUDE REGEX "/colormaps_data\\.h$")

# Relative to the source dir (which both targets run in): a failing check prints
# the command it ran, and 123 absolute paths bury the diagnostics that matter.
# Relative paths also make clang-format's file:line output clickable from a
# terminal opened at the repo root.
set(_met_format_rel "")
foreach(_f IN LISTS MET_FORMAT_SOURCES)
    file(RELATIVE_PATH _rel "${CMAKE_SOURCE_DIR}" "${_f}")
    list(APPEND _met_format_rel "${_rel}")
endforeach()
set(MET_FORMAT_SOURCES ${_met_format_rel})

add_custom_target(format
    COMMAND ${MET_CLANG_FORMAT} -i --style=file ${MET_FORMAT_SOURCES}
    COMMENT "Formatting ${CMAKE_SOURCE_DIR} with ${MET_CLANG_FORMAT}"
    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
    VERBATIM)

# --dry-run reports the edits it would make instead of applying them; --Werror
# turns those reports into a non-zero exit so the target actually fails a build.
add_custom_target(format-check
    COMMAND ${MET_CLANG_FORMAT} --dry-run --Werror --style=file ${MET_FORMAT_SOURCES}
    COMMENT "Checking formatting (run the 'format' target to fix)"
    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
    VERBATIM)

list(LENGTH MET_FORMAT_SOURCES _met_format_count)
message(STATUS
    "clang-format ${_met_cf_found_major}.x: 'format' and 'format-check' cover "
    "${_met_format_count} files")
